metadata101/dcat-ap

- .gitignore
- src/main/plugin/dcat-ap/loc/eng/labels.xml
- transifex/transform/loc.labels.xslt
- transifex/transifex.sh
Some potential work items afterwards:
- check for windows compatibility with xsltproc (perhaps run all dependencies over docker)
- start translation work in transifex, currently all strings are english
Related transifex resource: https://app.transifex.com/geonetwork/metadata101/dcat-ap_loc_labels/
> Transifex for XML resources

- src/main/plugin/dcat-ap/duplicate-metadata.xsl
- src/main/plugin/dcat-ap/index-fields/index.xsl
- src/main/plugin/dcat-ap/layout/config-editor.xml
- src/main/plugin/dcat-ap/layout/layout-custom-fields-concepts.xsl
- src/main/plugin/dcat-ap/layout/layout-custom-fields-sds.xsl
- src/main/plugin/dcat-ap/layout/layout-custom-fields.xsl
- src/main/plugin/dcat-ap/layout/layout.xsl
- src/main/plugin/dcat-ap/layout/utility-tpl-multilingual.xsl
- src/main/plugin/dcat-ap/templates/dcat-ap-vl-dataset.xml
- src/main/plugin/dcat-ap/templates/dcat-ap-vl-service.xml
- src/main/plugin/dcat-ap/templates/metadata-dcat-dataset.xml
- src/main/plugin/dcat-ap/templates/metadata-dcat-service.xml
- src/main/plugin/dcat-ap/update-fixed-info.xsl
* Allowed encoding for languages (`dcat:CatalogRecord/dct:language[1]/(@rdf:resource|skos:Concept/@rdf:about|dct:LinguisticSystem/@rdf:about)`):
```xml
<dcat:CatalogRecord>
<dct:language>
<dct:LinguisticSystem rdf:about="http://publications.europa.eu/resource/authority/language/FRE"/>
</dct:language>
<dct:language rdf:resource="http://publications.europa.eu/resource/authority/language/FRE"/>
<dct:language rdf:resource="http://publications.europa.eu/resource/authority/language/ENG"/>
<dct:language rdf:resource="http://publications.europa.eu/resource/authority/language/NLD"/>
<dct:language>
<skos:Concept rdf:about="http://publications.europa.eu/resource/authority/language/NLD">
<rdf:type rdf:resource="http://purl.org/dc/terms/LinguisticSystem"/>
<skos:prefLabel …
```
> Multilingual support

- src/main/plugin/dcat-ap/extract-relations.xsl
- src/main/plugin/dcat-ap/formatter/xsl-view/view.xsl
- src/main/plugin/dcat-ap/index-fields/index.xsl
- src/main/plugin/dcat-ap/layout/config-editor.xml
- src/main/plugin/dcat-ap/process/thumbnail-add.xsl
- src/main/plugin/dcat-ap/process/thumbnail-remove.xsl
* Use `foaf:page/foaf:Document` with an image png, gif, jpg extension to encode an overview
* Add overview manager to editor side panel
* Add overview in index 
* Add overview to record default and full view
> Support metadata thumbnails

- src/main/plugin/dcat-ap/layout/config-editor.xml
- src/main/plugin/dcat-ap/loc/dut/labels.xml
- src/main/plugin/dcat-ap/loc/dut/schematron-rules-dcat-ap-hvd-cardinalities.xml
- src/main/plugin/dcat-ap/loc/dut/schematron-rules-dcat-ap-hvd-rec.xml
- src/main/plugin/dcat-ap/loc/dut/schematron-rules-dcat-ap-hvd.xml
- src/main/plugin/dcat-ap/loc/dut/strings.xml
- src/main/plugin/dcat-ap/loc/eng/labels.xml
- src/main/plugin/dcat-ap/loc/eng/schematron-rules-dcat-ap-hvd-cardinalities.xml
- src/main/plugin/dcat-ap/loc/eng/schematron-rules-dcat-ap-hvd-rec.xml
- src/main/plugin/dcat-ap/loc/eng/schematron-rules-dcat-ap-hvd.xml
- src/main/plugin/dcat-ap/loc/eng/strings.xml
- src/main/plugin/dcat-ap/loc/fre/labels.xml
- src/main/plugin/dcat-ap/loc/fre/schematron-rules-dcat-ap-hvd-cardinalities.xml
- src/main/plugin/dcat-ap/loc/fre/schematron-rules-dcat-ap-hvd-rec.xml
- src/main/plugin/dcat-ap/loc/fre/schematron-rules-dcat-ap-hvd.xml
- src/main/plugin/dcat-ap/loc/fre/strings.xml
- src/main/plugin/dcat-ap/loc/ger/labels.xml
- src/main/plugin/dcat-ap/loc/ger/schematron-rules-dcat-ap-hvd-cardinalities.xml
- src/main/plugin/dcat-ap/loc/ger/schematron-rules-dcat-ap-hvd-rec.xml
- src/main/plugin/dcat-ap/loc/ger/schematron-rules-dcat-ap-hvd.xml
- src/main/plugin/dcat-ap/loc/ger/strings.xml
- src/main/plugin/dcat-ap/schema/dcat.xsd
- src/main/plugin/dcat-ap/schematron/schematron-rules-dcat-ap-hvd-cardinalities.sch
- src/main/plugin/dcat-ap/schematron/schematron-rules-dcat-ap-hvd-rec.sch
- src/main/plugin/dcat-ap/schematron/schematron-rules-dcat-ap-hvd.sch
- added translations
- added missing elements for DataService
- added hvd schematrons
I had a question @fxprunayre : you mentioned adding a fallback for the thesaurus dropdown menu, when the language is not available. An example would be dcatap:applicableLegislation, which doesn't have a `nl` label. Did you see this fallback happen in the core `XslUtil`, or would you solve it through the editor XSL?
> Tweaks and translations

- src/main/plugin/dcat-ap/present/csw/dcat-core.xsl
- src/main/plugin/dcat-ap/present/csw/dcat.xsl
- src/main/plugin/dcat-ap/present/csw/eu-dcat-ap-hvd.xsl
- src/main/plugin/dcat-ap/present/csw/eu-dcat-ap-mobility.xsl
- src/main/plugin/dcat-ap/present/csw/eu-dcat-ap.xsl
- src/main/plugin/dcat-ap/present/csw/eu-geodcat-ap-semiceu.xsl
- src/main/plugin/dcat-ap/present/csw/eu-geodcat-ap.xsl
- src/main/plugin/dcat-ap/present/csw/own.xsl
With the previous configuration there was no option to retrieve the DCAT-AP record in their own format.
Update `own` outputSchema to return the XML as it is in the database. It is not defined in the CSW spec and is a GeoNetwork specific `outputSchema`. There is no need to define brief, full and summary conversions when they are all the same.
When a CSW request is made (GetRecords or GetRecordById) in one of the DCAT related output schema (added in https://github.com/geonetwork/core-geonetwork/pull/7600) return the DCAT record as it is.
eg. http://localhost:8080/geonetwork/srv/fre/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&ID=f7106a8f-7a63-4521-bfb7-8125c8601c9b&outputSchema=http://www.w3.org/ns/dcat%23 return the same as …
> CSW output configuration for DCAT

- src/main/plugin/dcat-ap/update-fixed-info.xsl
I was encountering some records in VL that contained a plain date (yyyy-mm-dd) in the changeDate, which was incorrectly handled by format-dateTime which expects a full datetime. This should rectify the problem by checking for a date format and then passing it to the corresponding format-date function.
@CMath04 we discussed this previously but only now got round to fixing it - was probably the cause for the erroneous CSW updates in the case of select dcat records. Could you take a quick look at the change so we can merge?
> Handle changeDate that contains plain date

- src/main/plugin/dcat-ap/layout/config-editor.xml
Cf. https://www.w3.org/TR/skos-reference/#notations
It is not a multilingual element and can't have an `xml:lang` attribute (which was causing validation error).
> Configuration / skos:notation is a typed literal

- src/main/plugin/dcat-ap/layout/config-editor.xml
When using action for associated resource in main form, the configuration of the panel is required.
Cf. side panel configuration https://github.com/metadata101/dcat-ap/blob/main/src/main/plugin/dcat-ap/config/associated-panel/default.json#L31-L46
If not, here the search results was not displayed.
> Editor / Service / Link to dataset

- src/main/plugin/dcat-ap/layout/config-editor.xml
In general, service metadata do not have an overview.
> Editor / Service / No overview panel

- src/main/plugin/dcat-ap/layout/config-editor.xml
Necessary core change for this to work: https://github.com/geonetwork/core-geonetwork/pull/8685
Allows forcing the "fill in your own option..." to the end of the list and sort the rest alphabetically.
> Added sortLabel as an override for sorting when applicable

- src/main/plugin/dcat-ap/convert/thesaurus-transformation.xsl
- src/main/plugin/dcat-ap/layout/config-editor.xml
- src/main/plugin/dcat-ap/layout/dispatcher.xsl
- src/main/plugin/dcat-ap/layout/layout-custom-fields-concepts.xsl
When a field is using a thesaurus, it has to be configured in the `config-editor.xml` file in the `editor/fields/for` section
eg.
```xml
<editor>...
<fields>...
<for name="dcat:theme" use="thesaurus-list-picker">
<directiveAttributes
thesaurus="external.theme.datatheme"
xpath="/dcat:theme"
max=""
labelKey="dcat.addThemes"/>
</for>
```
User may want to configure thesaurus to be used on a per view basis (eg. when a view is specific to a profile). In such case, the field configuration can be overriden a field element.
eg.
```xml
<field xpath="/rdf:RDF/dcat:Catalog/dcat:dataset/dcat:Dataset/dcat:theme"
name="dcat:theme"
or="theme"
use="data-gn-keyword-picker"
in="/rdf:RDF/dcat:Catalog/dcat:dataset/dcat:Dataset">
<directiveAttributes
thesaurus="external.theme.vl-datatheme"
xpath="/dcat:theme" …
```
> Editor / Thesaurus / Add possibility to override configuration.

- src/main/plugin/dcat-ap/layout/config-editor.xml
A validation error was triggered due to `xml:lang` attribute.
> Editor / dct:created is not a multilingual field

- pom.xml
From now on, rebasing main onto vl/main should result in clean upgrade. VL is not running the `pom.xml` version of `core/main`, it needs to be kept separate.
> Overwriting the pom version for VL

- src/main/plugin/dcat-ap/loc/dut/schematron-rules-dcat-ap-rec.xml
- src/main/plugin/dcat-ap/loc/eng/schematron-rules-dcat-ap-rec.xml
- src/main/plugin/dcat-ap/loc/fre/schematron-rules-dcat-ap-hvd-rec.xml
- src/main/plugin/dcat-ap/loc/fre/schematron-rules-dcat-ap-rec.xml
- src/main/plugin/dcat-ap/loc/fre/schematron-rules-dcat-ap-vl-rec.xml
- src/main/plugin/dcat-ap/loc/fre/schematron-rules-mdcat-rec.xml
- src/main/plugin/dcat-ap/loc/ger/schematron-rules-dcat-ap-rec.xml
- src/main/plugin/dcat-ap/schematron/schematron-rules-mdcat-rec.sch
- src/main/plugin/dcat-ap/schematron/schematron-rules-mdcat.sch
Fixes for schematron rules:
- labels that contained errors
- removed profile check in the schematron, so it can be applied through schematroncriteria following the other schematrons
> VL - Feature/schematronrules fixes

- src/main/plugin/dcat-ap/formatter/xsl-view/view.xsl
Previous implementation rendered the `dcatap:applicableLegislation` uri bare, without a label, as it does not contain a concept / prefLabel in the XML itself. This PR modifies the view to take this into account, fetching the label from the thesaurus.
**before**
**after**
> Render dcatap:applicableLegislation label in view

- src/main/plugin/dcat-ap/index-fields/index.xsl
Now indexing `dcatap:applicableLegislation` to more reliably filter on HVD records in the facets.
This correctly functions with multiple definitions of `dcatap:applicableLegislation` and requires adding `applicableLegislation` to the list of `arrayFields` in GeoNetwork (https://agiv.visualstudio.com/Metadata/_git/MetadataGeonetwork/pullrequest/43423). Could you advise on whether this is the right approach @fxprunayre ? 
Previously, our facets depended on 1) ISO keyword ELI 2) DCAT HVD category. This would lead to inconsistent behaviour as you could have DCAT records with an HVD category defined, without defining the ELI, and still popping up in the facet.
> Index (HVD) ELI

- src/main/plugin/dcat-ap/present/csw/csw-brief.xsl
- src/main/plugin/dcat-ap/present/csw/csw-full.xsl
- src/main/plugin/dcat-ap/present/csw/csw-summary.xsl
DCAT records could not be deleted by CSW calls due to the UUID not being parsed properly (dc:identifier should be present in the CSW document as I understand). This seems to fix the situation:
- added `dc:type` for dataset and service
- added `dc:identifier` based on fileidentifier, following iso19139
Not sure what to do with `geonet:info` which was present before, perhaps unused at this point.
This can be tested with the following CSW call (modify target uuid):
```
POST {{gn_host}}/srv/dut/csw-publication
<?xml version="1.0" encoding="UTF-8"?>
<csw:Transaction service="CSW" version="2.0.2" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
xmlns:ogc="http://www.opengis.net/ogc"
xmlns:apiso="http://www.opengis.net/cat/csw/apiso/1.0">
<csw:Delete>
<csw:Constraint version="1.0.0"> …
```
> fixed csw-brief for dcat-ap

- README.md
- src/main/java/org/fao/geonet/schema/dcatap/DCATAPSchemaPlugin.java
- src/main/plugin/dcat-ap/config/associated-panel/dcatapcatalog.json
- src/main/plugin/dcat-ap/formatter/xsl-view/view.xsl
- src/main/plugin/dcat-ap/index-fields/index.xsl
- src/main/plugin/dcat-ap/layout/config-editor.xml
- src/main/plugin/dcat-ap/layout/layout-custom-fields-concepts.xsl
- src/main/plugin/dcat-ap/layout/layout.xsl
- src/main/plugin/dcat-ap/layout/utility-tpl-multilingual.xsl
- src/main/plugin/dcat-ap/layout/utility-tpl.xsl
- src/main/plugin/dcat-ap/loc/dut/labels.xml
- src/main/plugin/dcat-ap/loc/dut/strings.xml
- src/main/plugin/dcat-ap/loc/eng/labels.xml
- src/main/plugin/dcat-ap/loc/eng/strings.xml
- src/main/plugin/dcat-ap/loc/fre/labels.xml
- src/main/plugin/dcat-ap/loc/fre/strings.xml
- src/main/plugin/dcat-ap/loc/ger/labels.xml
- src/main/plugin/dcat-ap/loc/ger/strings.xml
- src/main/plugin/dcat-ap/process/sibling-add.xsl
- src/main/plugin/dcat-ap/process/sibling-remove.xsl
- src/main/plugin/dcat-ap/schema/dcat.xsd
- src/main/plugin/dcat-ap/schema/profiles/mdcat.xsd
- src/main/plugin/dcat-ap/schema/rdf.xsd
- src/main/plugin/dcat-ap/schematron/schematron-rules-dcat-ap-cardinalities.sch
- src/main/plugin/dcat-ap/templates/dcat-ap-vl-virtualcatalogue.xml
- src/main/plugin/dcat-ap/update-fixed-info-variables.xsl
- src/main/plugin/dcat-ap/update-fixed-info.xsl
- transifex/translations/dcat-ap_loc_labels/en_US.xml
- transifex/translations/dcat-ap_loc_strings/en_US.xml
A virtual catalog is a record describing a group of records. eg. a data space. For each attached records, some properties can be added eg. stars, keywords
A virtual catalog is a DCAT record not containing `dcat:Dataset|dcat:DataService`.
```xpath
exists(rdf:RDF[not(*/(dcat:Dataset|dcat:DataService))]/dcat:Catalog)
```
```xml
<rdf:RDF xmlns:schema="http://schema.org/"
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:skos="http://www.w3.org/2004/02/skos/core#"
xmlns:spdx="http://spdx.org/rdf/terms#"
xmlns:owl="http://www.w3.org/2002/07/owl#"
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:mobilitydcatap="https://w3id.org/mobilitydcat-ap"
xmlns:adms="http://www.w3.org/ns/adms#"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:locn="http://www.w3.org/ns/locn#" …
```
> Virtual catalog support

- src/main/plugin/dcat-ap/extract-uuid.xsl
- src/main/plugin/dcat-ap/layout/config-editor.xml
- src/main/plugin/dcat-ap/layout/layout.xsl
- src/main/plugin/dcat-ap/layout/utility-tpl-multilingual.xsl
- src/main/plugin/dcat-ap/process/sibling-add.xsl
- src/main/plugin/dcat-ap/set-uuid.xsl
- src/main/plugin/dcat-ap/templates/dcat-ap-vl-virtualcatalogue.xml
- src/main/plugin/dcat-ap/update-fixed-info-variables.xsl
- src/main/plugin/dcat-ap/update-fixed-info.xsl
- src/main/resources/config-spring-geonetwork.xml
* Register title xpath (used to set title on creation).
* Do not allow adding twice the same record or linking record to itself.
* Add label to associated record title.
* Template / Add conformity statement
* Retrieve virtual catalog record language in corresponding CatalogRecord (and not in Catalog language)
* Editor / Add action for title or description if missing
* Remove dcat:record not referenced as CatalogRecord (fix removal of associated record from the main form)
> Virtual catalog improvements

- src/main/plugin/dcat-ap/layout/layout-custom-fields-concepts.xsl
Add support for https://github.com/geonetwork/core-geonetwork/pull/8973
This makes the editor more robust for multilingual editing or when UI language is not the record language and avoid to display the alert box when keywords are not found in the UI language.
In DCAT keyword ids are stored in `@rdf:resource` or `*/@rdf:about` depending if the thesaurus is configured with `useReference` or not.
> Editor / Keywords / Use keyword id when available.

- src/main/plugin/dcat-ap/index-fields/index.xsl
When using the default angular JS view, the resource identifier was missing because the field was not properly indexed. In XSL, position starts at 1.
> Indexing / Fix resourceIdentifier to use the first available

- src/main/java/org/fao/geonet/schema/dcatap/DCATAPSchemaPlugin.java
- src/main/plugin/dcat-ap/config/associated-panel/dcatapcatalog.json
- src/main/plugin/dcat-ap/config/associated-panel/default.json
- src/main/plugin/dcat-ap/layout/config-editor.xml
- src/main/plugin/dcat-ap/process/sibling-add.xsl
- src/main/plugin/dcat-ap/process/sibling-remove.xsl
Encoding:
* When linking to an HTML page https://metadata.vlaanderen.be/srv/api/records/99954c0a-4ac4-56ad-a75e-a730d778ebaf (Title is extracted)
```xml
<dcat:record rdf:resource="https://metadata.vlaanderen.be/srv/api/records/99954c0a-4ac4-56ad-a75e-a730d778ebaf"/>
<dcat:CatalogRecord rdf:about="https://metadata.vlaanderen.be/srv/api/records/99954c0a-4ac4-56ad-a75e-a730d778ebaf">
<foaf:primaryTopic rdf:resource="https://metadata.vlaanderen.be/srv/api/records/99954c0a-4ac4-56ad-a75e-a730d778ebaf"/>
<dct:title xml:lang="nl">Het digitale bouwaanvragen archief</dct:title>
<dct:identifier>https://metadata.vlaanderen.be/srv/api/records/99954c0a-4ac4-56ad-a75e-a730d778ebaf</dct:identifier>
</dcat:CatalogRecord>
```
* When linking from an XML ISO document …
> Virtual Catalogue / Associated record / Add possibility to link to remote records.

- src/main/plugin/dcat-ap/schematron/schematron-rules-dcat-ap-vl.sch
- to be fixed in the shacl conversion: the non rec- file is also checking some cardinality which is incorrectly implemented for multilingual records
- disabling the check for now
> VL-only: incorrect multilingual schematron check
